<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

Question 1 Output are powers of Input matrix 

In [36]:
import numpy as np
mat = np.arange(25).reshape(5,5)
mat1 = mat**2
mat1

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [37]:
N=5
for i in range(5):
    print(mat[i]**(N-i-1))

[  0   1  16  81 256]
[125 216 343 512 729]
[100 121 144 169 196]
[15 16 17 18 19]
[1 1 1 1 1]


In [51]:
l=np.arange(1,11)
t=l*10
n=len(l)
k=4
j=n-k+1
print("l    ", *l, sep = " ")
print ("====", ("=="*(16)), sep=" ")
print("Input ", *t)
for i in range(j):
  m=int(round(((t[i]+t[i+1]+t[i+2]+t[i+3])/k),0))
  print("y",i+1, m,"=",t[i],"+",t[i+1],"+",t[i+2],"+",t[i+3],"/",k)

l     1 2 3 4 5 6 7 8 9 10
==== ================================
Input  10 20 30 40 50 60 70 80 90 100
y 1 25 = 10 + 20 + 30 + 40 / 4
y 2 35 = 20 + 30 + 40 + 50 / 4
y 3 45 = 30 + 40 + 50 + 60 / 4
y 4 55 = 40 + 50 + 60 + 70 / 4
y 5 65 = 50 + 60 + 70 + 80 / 4
y 6 75 = 60 + 70 + 80 + 90 / 4
y 7 85 = 70 + 80 + 90 + 100 / 4
